### ISSUE TITLE
Modification in Makefile of sw/ directory, for spmv-fp to work

### ISSUE THREAD

**Issue by pmpakos** [cornell-zhang/HiSparse#2]
Hello. 
Thank you for your work. I would like to suggest a little change to your Makefile (located [here](https://github.com/cornell-zhang/HiSparse/blob/master/sw/Makefile)).

For the implementations of floating-point spmv (float_pob, float_stall), you have to add **-DFP_POB** or **-DFP_STALL** accordingly to the CXXFLAGS, so that the compilation of **host** or **benchmark** completes succesfully.
These flags are already set [here](https://github.com/cornell-zhang/HiSparse/blob/master/spmv-fp/makefile), but not visible in the previously referred "main" functions in sw/ directory.

Thank you

**Comment by yxd97** [comment]
Thanks for your comments! Could you please show the error message you get? The `host.cpp` and `benchmark.cpp` programs are designed to work for all designs so they don't need to see the flags. The compilation works well on our end.

**Comment by yxd97** [comment]
Closed for being inactive.
