### ISSUE TITLE
Compilation Error while running make benchamrk

### ISSUE THREAD

**Issue by UbaidHunts** [cornell-zhang/HiSparse#4]
Hey

I am getting the following errors while running the compilation for benchmark.cpp. Apparently there are typos in the files.

RROR: [v++ 207-3777] use of undeclared identifier 'in_addr'; did you mean 'in_pld'? (/home/Documents/HiSparse/spmv/libfpga/shuffle.h:37:38)
ERROR: [v++ 207-3777] use of undeclared identifier 'in_addr'; did you mean 'in_pld'? (/home/Documents/HiSparse/spmv/libfpga/shuffle.h:115:38)
ERROR: [v++ 207-3777] use of undeclared identifier 'FS2PE'; did you mean 'SF2PE'? (/home/Documents/HiSparse/spmv/libfpga/spmv_cluster.h:216:29)
ERROR: [v++ 207-3777] use of undeclared identifier 'FS2PE'; did you mean 'SF2PE'? (/home/Documents/HiSparse/spmv/libfpga/spmv_cluster.h:223:35)
ERROR: [v++ 207-3777] use of undeclared identifier 'FS2PE'; did you mean 'SF2PE'? (/home/Documents/HiSparse/spmv/libfpga/spmv_cluster.h:216:29)
ERROR: [v++ 207-3777] use of undeclared identifier 'FS2PE'; did you mean 'SF2PE'? (/home/Documents/HiSparse/spmv/libfpga/spmv_cluster.h:223:35)

**Comment by yxd97** [comment]
Thank you! It should be fixed in 25878076c74a2a3d6eb2af4aaacaa73183f092f9. Please check.
